CREATE FUNCTION [dbo].[SF_EncryptedPassword]
(
	@password NVARCHAR(500),
	@salt NVARCHAR(250)
)
RETURNS VARBINARY(32)
AS
BEGIN
	RETURN HASHBYTES('SHA2_256',CONCAT(SUBSTRING(@salt,0,4),@password,SUBSTRING(@salt,4,4)))
END
